---
title: "how_to_use_tidybgc"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{how_to_use_tidybgc}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(tidybgc)
library(ncdf4)
library(dplyr)
library(tidyr)
library(magrittr)
library(stringr)
```

# Extract the date from the profile
<br>
The extract_date() function has been designed to output the date of the profile.

```{r}

nc_path <- "~/oao2016/admt/GDAC/coriolis/6902880/profiles/SD6902880_001.nc"
nc <- ncdf4::nc_open(nc_path)

get_date <- function(nc){
  juld <- ncvar_get(nc, "JULD")
  juldqc <- ncvar_get(nc, "JULD_QC")
  origin <- NA
  origin <- as.POSIXct("1950-01-01 00:00:00", order="ymdhms") #convert juld->time
  time <- NA
  time <- origin + juld*3600*24
  time <- lubridate::date(time)
  jd_qc <- NA
  jd_qc <- substr(ncvar_get(nc,"JULD_QC"),1,1)
  if(jd_qc == 1){
    return(time)
  }
  else{
    print('JULD QC is different of 1')
  }
  
  
}

date <- get_date(nc)
```


#Get QC from SD or BD

```{r}

get_qc <- function(vars, nc_path){
  nc <- nc_open(nc_path)
  qc_table <- data.frame('vars' = character(),
                         'qc'= numeric())
  
  for(i in vars){
    t <- ncvar_get(nc, paste(i, 'QC', sep = '_'))
  if(grepl('/SD[0-9]', nc_path)){
    qc_vec <- unlist(str_split(t, pattern = ''))
  }
  else if(grepl('/BD[0-9]', nc_path)){
    qc_vec <- unlist(str_split(t[[3]], pattern = ''))
  }
  qc_vec <- as.numeric(gsub(' ', NA, qc_vec))
  depth <- seq(1:length(qc_vec))
  qc_var <- data.frame('vars' = paste(i, '_qc'), 'qc' = qc_vec, 'depth' = depth)
  qc_table <- bind_rows(qc_table, qc_var)
  }
  
  qc_table <- pivot_wider(qc_table, names_from = 'vars', values_from = 'qc')
  nc_close(nc)
  return(qc_table)
}

my_qc_table <- get_qc(c('CHLA', 'CHLA_ADJUSTED'), nc_path)

```

#Extract data from SD profiles

```{r}
extract_sd <- function(nc_path, vars){
  nc <- nc_open(nc_path)
  float_name <- str_extract(nc_path, '[0-9]{6,}')
  long_df <- data.frame('depth' = numeric(), 'variable' = character(), value = numeric())
  for(i in vars){
    var <- ncvar_get(nc, i)
    depth <- seq(1, length(var))
    table <- data.frame('depth' = depth, 'variable' = i, 'value' = var)
    long_df <- bind_rows(long_df, table)
  }
  lon <- ncvar_get(nc, 'LONGITUDE')
  lat <- ncvar_get(nc, 'LATITUDE')
  date <- get_date(nc)
  final_df <- long_df %>% pivot_wider(names_from = 'variable', values_from = 'value') %>% 
    mutate('date' = date,
           'lon' = lon,
           'lat' = lat,
           'float' = float_name)
  qc_df <- get_qc(vars, nc_path)
  final_df <- left_join(final_df, qc_df, by = 'depth') %>% janitor::clean_names() %>% 
    dplyr::select(float, date, lon, lat, depth, everything())
  return(final_df)
}

my_clean_table <- extract_sd(nc_path, c("CHLA_ADJUSTED", "CDOM"))
head(my_clean_table)
```




